### ISSUE TITLE
Mind if I setup travis for you?

### ISSUE THREAD

**Issue by juliankrispel** [Rosey/markdown-draft-js#25]
so that you have CI in your prs?

**Comment by Rosey** [comment]
Yeah I do in fact have circleCI running when I open my own prs but as you have noticed it seems to not be running for other people's PRs 🤔  https://circleci.com/gh/Rosey/markdown-draft-js 

I just found a setting under the config called "build forked pull requests" that was previously turned off (I just turned it on!) so that may fix the issue

**Comment by juliankrispel** [comment]
awesome :+1:
