### ISSUE TITLE
Security vulernability reported on Snyk

### ISSUE THREAD

**Issue by mschipperheyn** [Rosey/markdown-draft-js#89]
I'm not sure if you guys are aware of this:

https://snyk.io/test/npm/markdown-draft-js/1.3.0

reports a security vulnerability on Snyk. It can be solved by upgrading the `underscore.string` dependency.

**Comment by Rosey** [comment]
Thanks @mschipperheyn it looks like the vulnerability is through remarkable https://github.com/jonschlinkert/remarkable/issues/310 and there's a pull request with a fix. Hopefully that gets merged soon and we can update our remarkable dependency :)

**Comment by jdalegonzalez** [comment]
@Rosey It appears that @jonschlinkert isn't ever interested in fixing this problem.  Is there another library you could use instead of remarkable?  I am willing to attempt a PR.

**Comment by Rosey** [comment]
Hmm I chose remarkable because it has really great support for custom markdown options (eg designing your own markdown syntax for things like mentions) which I wasn't able to find with other tools. If you know of another markdown parser that is equally flexible then it could be possible to switch 🙂 

I suppose another option is to fork remarkable and patch the vulnerabilities and use that fork instead of the original 😓

**Comment by jdalegonzalez** [comment]
I’m with you.  I like the library and in fact, I offered a PR to the author that met his initial request of ripping out argparse and replacing it with another library he’d identified.  He decided not to accept that PR (or any of the many others from other authors that followed.)  I can only assume that he is either trying to make a point, not interested in upkeep on this project or is working on a major re-write or something that obviates these changes.

 

This package seems really popular and well maintained.  I haven’t looked at custom syntax.

 

https://github.com/markedjs/marked

**Comment by jonschlinkert** [comment]
> I’m with you.  I like the library and in fact, I offered a PR to the author that met his initial request of ripping out argparse and replacing it with another library he’d identified.

If you did indeed do what you're saying, my apologies, I didn't ignore the PR intentionally. I would love to merge it and get rid of these issues. 

Can you link to the pr?

**Comment by jdalegonzalez** [comment]
Sure.

https://github.com/jonschlinkert/remarkable/pull/327

**Comment by Rosey** [comment]
https://github.com/Rosey/markdown-draft-js/pull/104 Updates to the latest version of remarkable which resolves 2 out of 3 security alerts on snyk.

**Comment by TrySound** [comment]
Is the third one comes from remarkable too?

**Comment by TrySound** [comment]
Ah, I see. It comes from autolinker. That dependency is evaluated a lot. I not sure it's safe to upgrade it in patch dependency. I will publish major bump soon. It will include autolinker upgrade.

**Comment by Rosey** [comment]
Thanks so much @TrySound  for knocking out that last one 🙂 

https://snyk.io/test/npm/markdown-draft-js/2.0.0 I think we're all clear (for now at least 🙃 )

did a major release bump for this one since the remarkable dependency was major and I didn't want to risk any backwards compatibility issues. However I don't _think_ there should be any.
